# Generated by Django 2.2.7 on 2019-11-07 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('goalkeeper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='target',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 7, 14, 53, 53, 966652, tzinfo=utc)),
        ),
    ]
