# Generated by Django 2.2.7 on 2019-11-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalkeeper', '0005_auto_20191108_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
